version: "3.5"

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ="${TZ}"
      - URL="${BASE_URL}"
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL="${EMAIL}"
    volumes:
      - ${BASE_BIND_DIR}/config/docker-letsencrypt:/config
      - ${BASE_BIND_DIR}/logs/docker-letsencrypt:/config/log
      - ./renewal-hooks:/config/etc/letsencrypt/renewal-hooks
      - ./site-confs:/config/nginx/site-confs
    ports:
      - 443:443
      - 80:80
    networks:
      bridge_net:
      reverse_proxy:
        aliases:
          - letsencrypt.proxy
    extra_hosts:
      - omv.proxy:${BRIDGE_GATEWAY}
    restart: always

networks:
  bridge_net:
    external: true
    name: ${BRIDGE_NETWORK}
  reverse_proxy:
    external: true
