version: "3"

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE="${MYSQL_DB}"
    networks:
      - internal

  redis:
    image: redis:buster
    restart: always
    networks:
      - internal

  app:
    build: ./nextcloud
    restart: always
    volumes:
      - app_data:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE="${MYSQL_DB}"
      - SMTP_HOST="${SMTP_HOST}"
      - SMTP_SECURE=SSL
      - SMTP_NAME="${SMTP_USERNAME}"
      - SMTP_PASSWORD="${SMTP_PASSWORD}"
      - MAIL_FROM_ADDRESS="${SMTP_FROM_ADDR}"
    depends_on:
      - db
      - redis
    networks:
      internal:
        aliases:
          - app.internal

  web:
    build: ./nginx
    restart: always
    volumes:
      - app_data:/var/www/html:ro
    depends_on:
      - app
    networks:
      internal:
      reverse_proxy:
        aliases:
          - nextcloud.proxy

volumes:
  db:
  app_data:

networks:
  internal:
  reverse_proxy:
    external:
      name: reverse_proxy
