version: "3"

services:
  db:
    image: mariadb:10
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE="${MYSQL_DB}"

  redis:
    image: redis:buster
    restart: always

  app:
    build: ./nextcloud
    restart: always
    volumes:
      - "nextcloud:/var/www/html"
      - "${APP_DATA}:/var/www/html/data"
      - "${APP_CONFIG}:/var/www/html/config"
    environment:
      - MYSQL_HOST=notmydb
      - REDIS_HOST=redis
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE="${MYSQL_DB}"
      - SMTP_HOST="${SMTP_HOST}"
      - SMTP_SECURE=SSL
      - SMTP_NAME="${SMTP_USERNAME}"
      - SMTP_PASSWORD="${SMTP_PASSWORD}"
      - MAIL_FROM_ADDRESS="${SMTP_FROM_ADDR}"
    depends_on:
      - db
      - redis
    networks:
      default:
        aliases:
          - app.internal

  web:
    build: ./nginx
    restart: always
    volumes:
      - "nextcloud:/var/www/html:ro"
    depends_on:
      - app
    labels:
      traefik.enable: "true"
      traefik.http.routers.nextcloud.rule: "Host(`${PUBLIC_HOSTNAME}`)"
      traefik.http.routers.nextcloud.entrypoints: "https"
      traefik.http.routers.nextcloud.tls.certresolver: "letsencrypt"
      traefik.http.routers.nextcloud.tls.domains[0].main: "${PUBLIC_HOSTNAME}"

volumes:
  db:
  nextcloud:
