version: "3"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: "${HOSTNAME}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${HOSTNAME}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    ports:
      - "22:22"
    networks:
      - reverse_proxy_external
    volumes:
      - /tank/config/gitlab:/etc/gitlab
      - /tank/logs/gitlab:/var/log/gitlab
      - /tank/app_data/gitlab:/var/opt/gitlab

networks:
  reverse_proxy_external:
    external: true
