version: '3'

services:
  znc:
    build: ./znc
    restart: always
    ports:
      - "6697:6697"
    volumes:
      - znc_data:/znc-data
    labels:
      traefik.enable: "true"
      traefik.http.routers.znc-web.rule: "Host(`${PUBLIC_HOSTNAME}`)"
      traefik.http.routers.znc-web.entrypoints: "https"
      traefik.http.routers.znc-web.tls: "true" # Should fallback to Let's Encrypt Certificate
      traefik.http.services.znc-web.loadbalancer.server.port: "8080"

volumes:
  znc_data:
