version: '3'

services:
  znc:
    build: ./znc
    restart: always
    volumes:
      - znc_data:/znc-data
    labels:
      traefik.enable: "true"
      traefik.http.routers.znc-web.rule: "Host(`${PUBLIC_HOSTNAME}`)"
      traefik.http.routers.znc-web.entrypoints: "https"
      traefik.http.routers.znc-web.tls: "true" # Should fallback to Let's Encrypt Certificate
      traefik.http.services.znc-web.loadbalancer.server.port: "8080"

      traefik.tcp.routers.znc-irc.rule: "HostSNI(`${PUBLIC_HOSTNAME}`)"
      traefik.tcp.routers.znc-irc.entrypoints: "irc"
      traefik.tcp.routers.znc-irc.tls: "true" # Should fallback to Let's Encrypt Certificate
      traefik.tcp.services.znc-irc.loadbalancer.server.port: "6667"

volumes:
  znc_data:
