version: "3"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB}"

  wordpress:
    build: ./wordpress
    volumes:
      - ./webroot/html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${MYSQL_DB}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_TABLE_PREFIX: "${WP_TABLE_PREFIX}"
    depends_on:
      - db
    restart: always
    networks:
      default:
        aliases:
          - wordpress.internal

  web:
    build: ./nginx
    restart: always
    volumes:
      - ./webroot/html:/var/www/html:ro
    depends_on:
      - wordpress
    labels:
      traefik.enable: "true"
      traefik.http.routers.wordpress.rule: "Host(`${PUBLIC_HOSTNAME}`)"
      traefik.http.routers.wordpress.entrypoints: "https"
      traefik.http.routers.wordpress.tls.certresolver: "letsencrypt"
      traefik.http.routers.wordpress.tls.domains[0].main: "${PUBLIC_HOSTNAME}"

volumes:
  db:
  app_data:
