version: "3.5"

services:
  jenkins:
    build:
      context: ./jenkins
      args:
        - DOCKER_GROUP_ID
    networks:
      internet:
    volumes:
      - home:/var/jenkins_home
      - ${DOCKER_SOCK}:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.routers.jenkins.rule: "Host(`${PUBLIC_HOSTNAME}`)"
      traefik.http.routers.jenkins.entrypoints: "https"
      traefik.http.routers.jenkins.tls: "true" # Should fallback to Let's Encrypt Certificate

volumes:
  home:

networks:
  internet: # specified to be explicit, and allow for adding IPv6 interfaces
    external:
      name: ${BRIDGE_NETWORK}
