version: "3.5"

services:
  jenkins:
    build:
      context: ./jenkins
      args:
        - DOCKER_GROUP_ID
    networks:
      reverse_proxy:
        aliases:
          - jenkins.proxy
      bridge_net:
    volumes:
      - home:/var/jenkins_home
      - ${DOCKER_SOCK}:/var/run/docker.sock

volumes:
  home:

networks:
  bridge_net:
    external: true
    name: ${BRIDGE_NETWORK}
  reverse_proxy:
    external: true
