version: "2.1"

services:
  jenkins:
    build:
      context: ./jenkins
      args:
        - DOCKER_GROUP_ID
    networks:
      reverse_proxy:
        aliases:
          - jenkins.proxy
      internet:
    volumes:
      - home:/var/jenkins_home
      - ${DOCKER_SOCK}:/var/run/docker.sock

volumes:
  home:

networks:
  internet:
    enable_ipv6: true
  reverse_proxy:
    external: true
